title: Yeonju Jung
logo: /assets/img/photo.jpg
description: Minimal is a theme for GitHub Pages. <br><br>
  <a href="https://www.linkedin.com/in/yeonjujung/">View my LinkedIn Profile</a> 

google_analytics:
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
