title: Yeonju Jung
logo: /assets/img/photo.jpg
description: Hi there! I’m Yeonju, a passionate Data Analyst with over 3 years of experience in data analysis, visualization, and business intelligence. I specialize in turning raw data into actionable insights using tools like SQL, Python, Tableau, and Excel. I created this portfolio to highlight my skills and share my journey with you. Take a look around, and feel free to connect! <br><br>
  <a href="https://www.linkedin.com/in/yeonjujung/">View my LinkedIn Profile</a> 

google_analytics:
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
